---
# Members of the group.
group:
  - name: Neha Naveen
    netid: njn43
  - name: Keti Sulamanidze
    netid: ks2469
  - name: Ruby Penafiel-Gutierrez
    netid: rsp227
  - name: Varvara Babii
    netid: vb348
  - name: Samantha Vaca
    netid: sv492

# Our PM.
pm:
  name: Sophia Wang
  netid: sw895
# Gallery entry is public.
publish: true
# Title.
title: " K-Means Classification Visualization in OCaml"
# Cornell Github link.
git-repo: "https://github.coecis.cornell.edu/ks2469/Ocaml_3110_GP"
# Demo video.
demo-video-url: "video link"
# Write a short, attention-grabbing description of your project.
desc: >
  Our project is an interactive K-Means Classification Visualizer. It supports
  K-means for points in 1D, 2D, and 3D. The interface allows users to offer a
  CSV file containing points they wish to cliassify, otherwise they may run
  the program on randomly generated points. Users may also choose their own
  value of k, or let the program choose it for them.

Standard visual I/O is supported, and outputs a graph for the user to see the various iterations of K-Means.
